# Generated by Django 3.1 on 2023-04-06 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weatherapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='messages',
            new_name='Email',
        ),
    ]
