# Generated by Django 3.1 on 2023-04-06 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weatherapp', '0002_auto_20230406_1143'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='Info',
        ),
    ]
